#!/bin/bash
if [ $# -ne 1 ]
then
echo "USAGE: findcrc filename"
echo " returns crc for file"
exit
return
fi
cat $1 | tr [a-z] [A-Z] | tr '\n' ' ' | xargs > pooma
sed -i 's/ /+/g' pooma
POOP=$(echo "obase=16;ibase=16;$(cat pooma)" | bc) ; echo ${POOP: -2}
sed -i "$ s/$/ $POOP/" $1

